### ISSUE TITLE
Masthead image zoom

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#13]
I made a new issue for this instead of adding this to #2 even though mastheads are a subject there - I figure we're going to have this issue whatever image we use?

On large monitors the mastheads zoom **a lot** and its no good

**Comment by domfarolino** [comment]
Well in regards to the current pictures I don't believe they're being stretched at all. On a ~24" monitor, if you look at the sides of the site, they are actually being repeated to avoid stretching. The reason the images are not big enough in the first place is because I took smaller copies of the pics the photographer took. If they don't look like their high quality enough that's because I compressed them (a lot).

On final, I think we should use `background-size: cover` to ensure they are not repeating and cover the entire screen. We can of course use larger images too, but my biggest worry is shipping too large a bundle to the client

**Comment by kurtlewis** [comment]
As long as you know what you're doing I'm good. I wanted to make sure this got an issue to track comments and discussion
