### ISSUE TITLE
Homepage content

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-website#19]
Required content:

- Masthead image area:
    - [x]   Name of hackathon (RevolutionUC)
    - [x]    Date (April 8th & 9th, 2017)
    - [x]    Location (University of Cincinnati)

~**Consider** adding masthead media queries so content doens't overlap on small screens~

- Body area

    - [ ]    Rich links to the about page, ~~FAQ page, schedule page, etc~~.
    - [ ]    Sponsors logos and links (include contact info for interested sponsors)
    - [ ]    Social media info
    - [ ]    Contact info

**Comment by domfarolino** [comment]
I don't think we should put the location in the masthead. We can talk more about it but I really don't like to see it too crowded especially if the pics take away from the text (or add too much noise to it)

**Comment by isiah-lloyd** [comment]
@domfarolino I kinda think having an address or location is important right and center (much like an regular invitation). The people who are visiting the site are those who want to register for a hackathon (which requires them to know where it is and when), or people who are already registered and need to quickly figure out where it is. 

More input from others would be nice.

**Comment by domfarolino** [comment]
Yeah I'm def willing to consider it. Just want to see it in action as long as its not too crowded. Agree with your comment on the font-weight. We're going to need to pull in more weights from the CDN or something though because we're at the min (100) right now (I believe). Sorry for kinda jacking the subtitle stuff in my PR lol didn't pay attn. You want me to revert masthead changes from my PR and we can turn the PR into a pure body-styles one so you can take masthead + home content?

**Comment by domfarolino** [comment]
Reasoning for less content on masthead: https://developer.chrome.com/devsummit/location - maybe we should have a page dedicated to location? Noah can provide more input. Tomorrow I'll revert masthead changes and leave the PR a body-styles one.

**Comment by isiah-lloyd** [comment]
That sounds good to me, just so we can merge this one and talk more about
the subtitles

**Comment by isiah-lloyd** [comment]
What did you mean by rich links for About, FAQ, etc.

**Comment by isiah-lloyd** [comment]
@domfarolino Did you remove the two first tasks from this issue? Did you already make the register call to action? I had this whipped up: 
![image](https://cloud.githubusercontent.com/assets/885544/21951218/bdf3c5a4-d9d1-11e6-8209-76134d1cba52.png)

**Comment by domfarolino** [comment]
Yeah sorry did you see the registration notification button live on bosley? This resulted from an earlier PR that me and @noahbass did this week with content styles. It was an impromptu thing we did and we must've not realized it was in this issue. That's something we should've caught before looking at registration notification button styles but didn't sorry. The second thing I removed was something I think @ noah was doing in his latest PR (not pushed yet) so I didn't want it to get duped.

Need to communicate this stuff better and not dupe work...sorry man.

Also I added strike-through text on the rich links in the issue description since we do not have those pages now.

**Comment by isiah-lloyd** [comment]
@domfarolino Should I keep these styles around for once we have the actual registration form ready?

**Comment by domfarolino** [comment]
What styles do you have so far? You can push a branch so we can check it out if you want

**Comment by isiah-lloyd** [comment]
@domfarolino I just got started on it last night: https://github.com/RevolutionUC/revolutionuc-website/tree/feature/homepage-content-body-content

**Comment by domfarolino** [comment]
@noahbass are we closing this?
