### ISSUE TITLE
Database Dashboard

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#62]
It would be super cool to have a dashboard for viewing who has regsitered for the event. This needs to be well protected. It should also be sortable.

**Comment by domfarolino** [comment]
Who all would be using this and for what purpose? I ask because I have a simple solution right now that requires no developer work however it is not the most user-friendly thing...this is OK with me if it is not meant to be used by people outside of the dev team, as it is a fairly low-priority issue.

**Comment by kurtlewis** [comment]
depends on how other issues are resolved...

This could be a way to solve number 4 on #60, in which case its probably easier for the web team to make it accessible to logistics, otherwise the web team is going to end up doing a lot of that work. We'll also need a way to move single people off the waitlist by email. This again might be the easiest way to accomplish that. [I'm amending #60 now to include that information]

Regardless, this isn't a priority issue to make a super cool table or anything.
